-- ================================================================
-- AFTER5 SEED DATA
-- ================================================================
--
-- NOTE: All seed data has been moved to migrations for proper version control.
-- The data is now in: supabase/migrations/20260114000001_seed_initial_data.sql
--
-- This file is kept for reference but should not contain any SQL statements
-- that would conflict with the migration data.
--
-- To seed a fresh database, run the migrations instead:
--   supabase db push
--
-- To reset and seed a local database:
--   supabase db reset
-- ================================================================